# Generated by Django 4.1.7 on 2023-03-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='picture',
        ),
    ]
