# Generated by Django 4.1.7 on 2023-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_plate_image_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.CharField(default='food/static/food/images/food_placeholder.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default='food/static/food/images/restaurant_placeholder.avif', max_length=500),
        ),
    ]
