# Generated by Django 4.1.7 on 2023-04-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_plate_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='image',
            field=models.CharField(default='https://goodviewvictoria.com/img/placeholders/comfort_food_placeholder.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(default='https://cdn0.iconfinder.com/data/icons/map-and-location-16/512/restaurant-cup-food-location-lunch-map-restaurant-512.png', max_length=500),
        ),
    ]
