# Generated by Django 4.1.7 on 2023-05-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_plate_image_alter_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='available',
        ),
    ]
